version: '3.8'

services:
  auth-db:
    image: postgres:15-alpine
    container_name: authDb
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: password
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - innowise-network
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U auth -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  authservice:
    build: .
    container_name: authService
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: password
      JWT_SECRET: 6shbWQHObScqHQrtucGnJSgKZxaWnvVmI43YiTQWyyL
      ACCESS_TOKEN_EXPIRATION: PT15M
      REFRESH_TOKEN_EXPIRATION: P1D


    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - innowise-network

    depends_on:
      auth-db:
        condition: service_healthy
networks:
  innowise-network:
    driver: bridge

volumes:
  auth-data: