spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${SERVER_PORT:8082}

jwt:
  access-expiration: ${ACCESS_TOKEN_EXPIRATION:PT15M}
  refresh-expiration: ${REFRESH_TOKEN_EXPIRATION:P7D}