spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://auth-db:5432/authdb}
    username: ${POSTGRES_USER:auth}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET:6shbWQHObScqHQrtucGnJSgKZxaWnvVmI43YiTQWyyL}
  access-expiration: ${ACCESS_TOKEN_EXPIRATION:PT15M}
  refresh-expiration: ${REFRESH_TOKEN_EXPIRATION:P1D}